#!/bin/env python
# -*- coding: utf-8 -*-

""" latex2orgmode:  Try to convert LaTeX to Orgmode.
    2022-02-23, MvdS: initial version.
"""

# PYTHON_ARGCOMPLETE_OK


import colored_traceback
colored_traceback.add_hook()

import re



def main():
    """Main function."""
    
    infile,outfile = get_arguments()
    file_latex_to_orgmode(infile, outfile)
    
    exit(0)


def get_arguments():
    """Get CLI arguments.
    
    Parameters:
    
    Returns:
      (str):  Input file name.
      (str):  Output file name.
    """
    
    import argparse
    import argcomplete
    import sys
    
    # Parse command-line arguments:
    parser = argparse.ArgumentParser(description="Try to convert a LaTeX file to Orgmode.",
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)  # Use capital, period, add default values
    
    # Required arguments:
    parser.add_argument("infile", type=str, default=None, help="name of the input LaTeX file (file.tex)")
    parser.add_argument("-o", "--outfile", type=str, default=None, help="name of the output Orgmode file (file.org)")
    
    parser.add_argument("-v", "--verbosity", action="count", default=0, help="increase output verbosity")  # Counts number of occurrences
    
    argcomplete.autocomplete(parser)
    args = parser.parse_args()
    
    if args.outfile is None:
        outfile = re.sub(r'\.org\.org',r'.org', re.sub(r'\.tex',r'.org', str(args.infile))+'.org')
    else:
        outfile = args.outfile
        
    if args.infile == outfile:
        sys.stderr.write('Input and output file have the same name: '+outfile+'\n')
        
    print('Input file:  '+args.infile)
    print('Output file: '+outfile)
    
    return args.infile, outfile


def file_latex_to_orgmode(infile, outfile):
    """Covert lines of text from LaTeX format to Orgmode format.
    
    Parameters:
      infile (str):   Name of the input file.
      outfile (str):  Name of the output file.
    """
    
    # Open the input and output files:
    # ifl = open(infile, 'r')
    ofl = open(outfile,'w')
    ofl.write('# #+startup: latexpreview  # Note: this may take a looong time when uncommented...\n')
    
    iline = 0
    with open(infile, 'r') as lines:
        try:
            while True:
                iline += 1
        
                # Read data line and extract column contents:
                # line = ifl.readline()
                line = next(lines)
                
                line = line_latex_to_orgmode(line)
                
                ofl.write('%s' % (line))
                # print(iline, line)
        except StopIteration:
            print(str(iline)+' lines processed.')
            exit
    
    return


def line_latex_to_orgmode(line):
    """Convert a line of LaTeX code to Orgmode.

    Parameters:  
      line (str):  The line containing LaTeX code.

    Returns:  
      (str):  A line containing Orgmode code.
    """
    
    # line = re.sub(r'^ *\n', r'', line)  # Remove empty lines - CHECK remove this code line later!
    
    # Preamble:
    line = re.sub(r'^.*\\documentclass.*\n', r'', line)
    line = re.sub(r'^.*\\usepackage.*\n', r'', line)
    line = re.sub(r'^.*\\input.*\n', r'', line)
    line = re.sub(r'^.*\\graphicspath.*\n', r'', line)
    line = re.sub(r'^ *%.*\n', r'', line)
    line = re.sub(r'^.*\\pdfinfo.*\n', r'', line)
    line = re.sub(r'^ */[A-Z][a-z]* *\(.*\) *\}*\n', r'', line)  # PDFinfo lines, like " /Title (<title>)"
    line = re.sub(r'^.*\\ifthenelse.*\n', r'', line)
    line = re.sub(r'^.*\\geometry.*\n', r'', line)
    line = re.sub(r'^ *\} *\n', r'', line)  # PDFinfo lines, like " /Title (<title>)"
    line = re.sub(r'^.*\\pagestyle.*\n', r'', line)
    line = re.sub(r'^.*\\makeatletter.*\n', r'', line)
    line = re.sub(r'^.*\\makeatother.*\n', r'', line)
    line = re.sub(r'^.*\\newcommand.*\n', r'', line)
    line = re.sub(r'^.*\\renewcommand.*\n', r'', line)
    line = re.sub(r'^.*\\bibliography.*\n', r'', line)
    line = re.sub(r'^.*\\DeclareRobustCommand.*\n', r'', line)
    line = re.sub(r'^.*\\tableofcontents.*\n', r'', line)
    line = re.sub(r'^.*\\onehalfspacing.*\n', r'', line)
    line = re.sub(r'^.*\\definecolor[\[{].*\n', r'', line)  # Followed by [ or {
    line = re.sub(r'^.*\\color[\[{].*\n', r'', line)
    line = re.sub(r'^.*\\fancyhead[\[{].*\n', r'', line)
    line = re.sub(r'^.*\\fancyfoot[\[{].*\n', r'', line)
    
    # Title, author, etc:
    line = re.sub(r'\\title[* ]*\{([^}]*)\}',  r'#+title:  \1', line)
    line = re.sub(r'\\author[* ]*\{([^}]*)\}', r'#+author: \1', line)
    line = re.sub(r'\\email[* ]*\{([^}]*)\}',  r'#+email:  \1', line)
    line = re.sub(r'\\date[* ]*\{([^}]*)\}',   r'#+date:   \1', line)
    line = re.sub(r'^ \\titlepage *\n',   r'', line)
    line = re.sub(r' *\\titlepage *',   r'', line)
    
    # Text colour:
    line = re.sub(r'^ *\\SetRowColor\{[^}]*\} *\n', r'', line)
    line = re.sub(r' *\\SetRowColor\{[^}]*\} *', r'', line)
    line = re.sub(r' *\\textcolor\{[^}]*\} *', r'', line)
    line = re.sub(r' *\\hhline\{>\{\\arrayrulecolor\{[^}]*\}\}--\} *', r'----', line)
    line = re.sub(r' *\\hhline\{>\{\}--\} *', r'----', line)
    line = re.sub(r'^ *\\hline *$', r'----', line)
    line = re.sub(r' *\\arrayrulecolor\{[^}]*\} *', r'', line)
    
    
    # Resolve aliases/macros/newcommands:
    line = re.sub(r'^\\bel *\{([^}]*)\}', r'\n\\label{\1}\n\\begin{equation}', line)  # \bel = \begin{eq} + \label
    
    line = re.sub(r'^\\be$', r'\\begin{equation}', line)  # \be = \begin{eq}
    line = re.sub(r'^\\ee$', r'\\end{equation}', line)  # \be = \begin{eq}
    line = re.sub(r'^\\be ', r'\\begin{equation}', line)  # \be = \begin{eq}
    line = re.sub(r'^\\ee ', r'\\end{equation}', line)  # \be = \begin{eq}
    
    # eqnarray is unknown to Orgmode; rename it equation:
    line = re.sub(r'^\\bal *\{([^}]*)\}', r'\n\\label{\1}\n\\begin{equation}', line)  # \bel = \begin{eq} + \label
    line = re.sub(r'^\\bael *\{([^}]*)\}', r'\n\\label{\1}\n\\begin{equation}', line)  # \bel = \begin{eq} + \label
    
    line = re.sub(r'^\\bea$', r'\\begin{equation}', line)  # \be = \begin{eqnarray}
    line = re.sub(r'^\\eea$', r'\\end{equation}', line)  # \be = \begin{eqnarray}
    line = re.sub(r'^\\bea ', r'\\begin{equation}', line)  # \be = \begin{eqnarray}
    line = re.sub(r'^\\eea ', r'\\end{equation}', line)  # \be = \begin{eqnarray}
    
    line = re.sub(r'^\\ba$', r'\\begin{equation}', line)  # \be = \begin{eqnarray}
    line = re.sub(r'^\\ea$', r'\\end{equation}', line)  # \be = \begin{eqnarray}
    line = re.sub(r'^\\ba ', r'\\begin{equation}', line)  # \be = \begin{eqnarray}
    line = re.sub(r'^\\ea ', r'\\end{equation}', line)  # \be = \begin{eqnarray}
    
    
    # References to equations:
    line = re.sub(r'( [Ee]quations*)[~ ]\(([^)]*)\)', r'\1 \2', line)
    line = re.sub(r'( [Ee]quations*)\\,\(([^)]*)\)', r'\1 \2', line)
    line = re.sub(r'( [Ee]quations*)[~ ]', r'\1 ', line)
    line = re.sub(r'( [Ee]quations*)\,', r'\1 ', line)
    
    line = re.sub(r'( [Ee]qs*)\.*[~ ]\(([^)]*)\)', r'\1.\2', line)
    line = re.sub(r'( [Ee]qs*)\.*\\,\(([^)]*)\)', r'\1.\2', line)
    line = re.sub(r'( [Ee]qs*)\.*[~ ]', r'\1.', line)
    line = re.sub(r'( [Ee]qs*)\.*\,', r'\1.', line)
    
    # References to figures:
    line = re.sub(r'( [Ff]igures*)[~ ]\(([^)]*)\)', r'\1 \2', line)
    line = re.sub(r'( [Ff]igures*)\\,\(([^)]*)\)', r'\1 \2', line)
    line = re.sub(r'( [Ff]igures*)[~ ]', r'\1 ', line)
    line = re.sub(r'( [Ff]igures*)\,', r'\1 ', line)
    
    line = re.sub(r'( [Ff]igs*)\.*[~ ]\(([^)]*)\)', r'\1.\2', line)
    line = re.sub(r'( [Ff]igs*)\.*\\,\(([^)]*)\)', r'\1.\2', line)
    line = re.sub(r'( [Ff]igs*)\.*[~ ]', r'\1.', line)
    line = re.sub(r'( [Ff]igs*)\.*\,', r'\1.', line)
    
    # References to tables:
    line = re.sub(r'( [Tt]ables*)[~ ]\(([^)]*)\)', r'\1 \2', line)
    line = re.sub(r'( [Tt]ables*)\\,\(([^)]*)\)', r'\1 \2', line)
    line = re.sub(r'( [Tt]ables*)[~ ]', r'\1 ', line)
    line = re.sub(r'( [Tt]ables*)\,', r'\1 ', line)
    
    line = re.sub(r'( [Tt]abs*)\.*[~ ]\(([^)]*)\)', r'\1.\2', line)
    line = re.sub(r'( [Tt]abs*)\.*\\,\(([^)]*)\)', r'\1.\2', line)
    line = re.sub(r'( [Tt]abs*)\.*[~ ]', r'\1.', line)
    line = re.sub(r'( [Tt]abs*)\.*\,', r'\1.', line)
    
    # Spaces:
    line = re.sub(r'\~', r' ', line)
    line = re.sub(r'\\,', r' ', line)
    
    # Cetera:
    line = re.sub(r'^.*\\maketitle.*\n', r'', line)
    line = re.sub(r'^.*\\setcounter[\[{].*\n', r'', line)
    line = re.sub(r'^.*\\setlength[\[{].*\n', r'', line)
    line = re.sub(r'^.*\\newlength[\[{].*\n', r'', line)
    line = re.sub(r'^.*\\addtolength[\[{].*\n', r'', line)
    line = re.sub(r'^.*\\raggedleft.*\n', r'', line)
    line = re.sub(r'^.*\\raggedright.*\n', r'', line)
    line = re.sub(r'^ *\\raggedcolumns *\n', r'', line)
    line = re.sub(r'^ *\\vspace\**\{[^}]*\} *\n', r'\n\n', line)
    line = re.sub(r' *\\vspace\**\{[^}]*\} *', r'\n\n', line)
    line = re.sub(r'^ *\\addvspace\**\{[^}]*\} *\n', r'\n\n', line)
    line = re.sub(r' *\\addvspace\**\{[^}]*\} *', r'\n\n', line)
    line = re.sub(r'^ *\\hspace\**\{[^}]*\} *\n', r'', line)
    line = re.sub(r' *\\hspace\**\{[^}]*\} *', r'', line)
    line = re.sub(r'\\vfill', r'', line)
    line = re.sub(r'^ *\\noindent *\n', r'', line)
    line = re.sub(r' *\\noindent *', r'', line)
    line = re.sub(r' *\\parbox\{[^}]*\} *', r'', line)
    line = re.sub(r'^ *\\par *\n', r'', line)
    line = re.sub(r' *\\par *', r'', line)
        
    line = re.sub(r'\} *\\label *\{([^}]*)\}', r'}\n\\label{\1}', line)  # Move trailing \label{} to its own line
    
    
    # Begin/end stuff:
    line = re.sub(r'^.*\\begin\{document\}.*\n', r'', line)
    line = re.sub(r'^.*\\end\{document\}.*\n', r'', line)
    line = re.sub(r'^.*\\begin\{center\}.*\n', r'', line)
    line = re.sub(r'^.*\\end\{center\}.*\n', r'', line)
    line = re.sub(r'^.*\\begin\{tiny\}.*\n', r'', line)
    line = re.sub(r'^.*\\end\{tiny\}.*\n', r'', line)
    line = re.sub(r'^.*\\begin\{footnotesize\}.*\n', r'', line)
    line = re.sub(r'^.*\\end\{footnotesize\}.*\n', r'', line)
    line = re.sub(r'^.*\\begin\{scriptsize\}.*\n', r'', line)
    line = re.sub(r'^.*\\end\{scriptsize\}.*\n', r'', line)
    line = re.sub(r'^.*\\begin\{normalsize\}.*\n', r'', line)
    line = re.sub(r'^.*\\end\{normalsize\}.*\n', r'', line)
    line = re.sub(r'^.*\\begin\{[Ll]arge\}.*\n', r'', line)
    line = re.sub(r'^.*\\end\{[Ll]arge\}.*\n', r'', line)
    line = re.sub(r'^.*\\begin\{LARGE\}.*\n', r'', line)
    line = re.sub(r'^.*\\end\{LARGE\}.*\n', r'', line)
    line = re.sub(r'^.*\\begin\{[Hh]uge\}.*\n', r'', line)
    line = re.sub(r'^.*\\end\{[Hh]uge\}.*\n', r'', line)
    
    # Figures:
    line = re.sub(r'^.*\\begin\{figure.*\n', r'', line)
    line = re.sub(r'^.*\\end\{figure.*\n', r'', line)
    line = re.sub(r'\\pgfimage\[[^]]*\]\{([^}]*)\}', r'[[file:\1]]', line)
    line = re.sub(r'\\pgfimage\{([^}]*)\}', r'[[file:\1]]', line)
    line = re.sub(r'\\includegraphics\[[^]]*\]\{([^}]*)\}', r'[[file:\1]]', line)
    line = re.sub(r'\\includegraphics\{([^}]*)\}', r'[[file:\1]]', line)
    
    # Tables:
    line = re.sub(r'^.*\\begin\{table.*\n', r'', line)
    line = re.sub(r'^.*\\end\{table.*\n', r'', line)
    line = re.sub(r'^.*\\begin\{tabular.*\n', r'', line)
    line = re.sub(r'^.*\\end\{tabular.*\n', r'', line)
    line = re.sub(r'^.*\\begin\{multicols.*\n', r'', line)
    line = re.sub(r'^.*\\end\{multicols.*\n', r'', line)
    line = re.sub(r'\\columnbreak', r'', line)
    
    line = re.sub(r'^ *\\\\\[[0-9.\-]*[cme]m\] *\n', r'', line)  # Extra space between table rows
    line = re.sub(r'^ *\[[0-9.\-]*[cme]m\] *\n', r'', line)
    line = re.sub(r'\\\\\[[0-9.\-]*[cme]m\] *$', r'', line)
    line = re.sub(r'\[[0-9.\-]*[cme]m\] *$', r'', line)
    line = re.sub(r'\\\\\[[0-9.\-]*[cme]m\]', r'', line)
    line = re.sub(r'\[[0-9.\-]*[cme]m\]', r'', line)
    
    line = re.sub(r'\\mymulticolumn\{[^}]*\}\{[^{]*\{[^}]*\}\}\{[^{]*\{([^}]*)\}\}', r'\1', line)
    line = re.sub(r'\\mymulticolumn\{[^}]*\}\{[^{]*\{[^}]*\}\}\{([^}]*)\}', r'\1', line)
    
    
    line = re.sub(r'\\centering', r'', line)
    line = re.sub(r'\\caption\{', r'Caption: ', line)
    
    # Colorbox (could be around figure removed above (in Beamer)): 
    line = re.sub(r'\\colorbox\[[^]]*\]\{[^}]*\}\{([^}]*)\}', r'\1', line)
    line = re.sub(r'\\colorbox\{[^}]*\}\{([^}]*)\}', r'\1', line)
   
    
    # Lists:
    line = re.sub(r'^.*\\begin\{itemize.*\n', r'', line)
    line = re.sub(r'^.*\\end\{itemize.*\n', r'', line)
    line = re.sub(r'^.*\\begin\{enumerate.*\n', r'', line)
    line = re.sub(r'^.*\\end\{enumerate.*\n', r'', line)
    line = re.sub(r'^.*\\begin\{description.*\n', r'', line)
    line = re.sub(r'^.*\\end\{description.*\n', r'', line)
    line = re.sub(r'\\item\[([^]]*)\] *', r'+ \1 :: ', line)
    line = re.sub(r'\\item *', r'+ ', line)
    
    # Verbatim:
    line = re.sub(r'^.*\\begin\{verbatim.*\n', r'#+begin_src text\n', line)
    line = re.sub(r'^.*\\end\{verbatim.*\n', r'#+end_src text\n', line)
    
    # Appendices:
    line = re.sub(r'^.*\\begin\{appendices.*\n', r'', line)
    line = re.sub(r'^.*\\end\{appendices.*\n', r'', line)
    line = re.sub(r'\\appendix', r'', line)
    
    # Font size:
    line = re.sub(r'\\tiny', r'', line)
    line = re.sub(r'\\footnotesize', r'', line)
    line = re.sub(r'\\small', r'', line)
    line = re.sub(r'\\normalsize', r'', line)
    line = re.sub(r'\\large', r'', line)
    line = re.sub(r'\\Large', r'', line)
    line = re.sub(r'\\LARGE', r'', line)
    line = re.sub(r'\\huge', r'', line)
    line = re.sub(r'\\Huge', r'', line)
    
    # line = re.sub(r'\\newline', r'\n', line)  # '\n' will not match $ later
    line = re.sub(r'\\newline', r'', line)
    line = re.sub(r'\\pagebreak', r'', line)
    line = re.sub(r'\\newpage', r'', line)
    line = re.sub(r'^.*\\newtheorem\{.*\n', r'', line)
    
    # Chapters, sections and paragraphs:
    line = re.sub(r'^ *\\chapter[* ]*\{\} *\n', r'', line)
    line = re.sub(r'^ *\\section[* ]*\{\} *\n', r'', line)
    line = re.sub(r'^ *\\subsection[* ]*\{\} *\n', r'', line)
    line = re.sub(r'^ *\\subsubsection[* ]*\{\} *\n', r'', line)
    line = re.sub(r'^ *\\paragraph[* ]*\{\} *\n', r'', line)
    
    line = re.sub(r' *\\chapter[* ]*\{\} *', r'', line)
    line = re.sub(r' *\\section[* ]*\{\} *', r'', line)
    line = re.sub(r' *\\subsection[* ]*\{\} *', r'', line)
    line = re.sub(r' *\\subsubsection[* ]*\{\} *', r'', line)
    line = re.sub(r' *\\paragraph[* ]*\{\} *', r'', line)
    
    line = re.sub(r'^ *\\chapter[* ]*\{([^}]*)\} *\n', r'\n* \1', line)
    line = re.sub(r'^ *\\section[* ]*\{([^}]*)\} *\n', r'\n* \1', line)
    line = re.sub(r'^ *\\subsection[* ]*\{([^}]*)\} *\n', r'\n** \1', line)
    line = re.sub(r'^ *\\subsubsection[* ]*\{([^}]*)\} *\n', r'\n*** \1', line)
    line = re.sub(r'^ *\\paragraph[* ]*\{([^}]*)\} *\n', r'\n**** \1', line)
    
    line = re.sub(r' *\\chapter[* ]*\{([^}]*)\} *', r'\n* \1', line)
    line = re.sub(r' *\\section[* ]*\{([^}]*)\} *', r'\n* \1', line)
    line = re.sub(r' *\\subsection[* ]*\{([^}]*)\} *', r'\n** \1', line)
    line = re.sub(r' *\\subsubsection[* ]*\{([^}]*)\} *', r'\n*** \1', line)
    line = re.sub(r' *\\paragraph[* ]*\{([^}]*)\} *', r'\n**** \1', line)
    
    line = re.sub(r'^ *\\textbf[* ]*\{([^}]*)\} *$', r'\n**** \1', line)  # full-line \textbf appears to be used as a paragraph
    
    # Beamer frames/slides:
    line = re.sub(r'^.*\\frame[\[{].*\n', r'', line)  # Followed by [ or {
    line = re.sub(r'^ *\\frametitle[* ]*\{([^}]*)\} *\n', r'\n*** \1', line)  # Assume \section and \subsection are converted to * and **
    line = re.sub(r' *\\frametitle[* ]*\{([^}]*)\} *', r'\n*** \1', line)  # Assume \section and \subsection are converted to * and **
    
    line = re.sub(r'^ *\\begin\{block\}[* ]*\{\} *\n', r'', line)  # Block w/o title -> nothing
    line = re.sub(r' *\\begin\{block\}[* ]*\{\} *', r'', line)  # Block w/o title -> nothing
    line = re.sub(r'^ *\\begin\{block\}[* ]*\{([^}]*)\} *\n', r'\n**** \1', line)  # Assume \section, \subsection and \frametitle are converted to *, ** and ***
    line = re.sub(r' *\\begin\{block\}[* ]*\{([^}]*)\} *', r'\n**** \1', line)  # Assume \section, \subsection and \frametitle are converted to *, ** and ***
    line = re.sub(r'^ *\\end\{block\} *\n', r'', line)
    
    line = re.sub(r'^ *\\begin\{columns\}[* ]* *\n', r'', line)
    line = re.sub(r'^ *\\end\{columns\} *\n', r'', line)
    line = re.sub(r'^ *\\begin\{column\}[* ]*\{.*\} *\n', r'', line)
    line = re.sub(r'^ *\\end\{column\} *\n', r'', line)
    
    line = re.sub(r'^ *\\uncover<[0-9]*->\{ *\n', r'', line)
    line = re.sub(r'\\uncover<[0-9]*->\{', r'', line)
    
    # My Beamer macros:
    line = re.sub(r'\{\\bluetext ([^{}]*)\}', r' blue: \1', line)
    line = re.sub(r'\{\\redtext ([^{}]*)\}', r' red: \1', line)
    line = re.sub(r'\{\\purpletext ([^{}]*)\}', r' purple: \1', line)
    line = re.sub(r'\{\\greentext ([^{}]*)\}', r' green: \1', line)
    line = re.sub(r'\{\\yellowtext ([^{}]*)\}', r' yellow: \1', line)
    line = re.sub(r'\\bluetext ', r'blue: ', line)
    line = re.sub(r'\\redtext ', r'red: ', line)
    line = re.sub(r'\\purpletext ', r'purple: ', line)
    line = re.sub(r'\\greentext ', r'green: ', line)
    line = re.sub(r'\\yellowtext ', r'yellow: ', line)
    line = re.sub(r'\\normaltext', r'', line)
    
    # Labels and references:
    line = re.sub(r'\\label[* ]*\{([^}]*)\}', r'label:\1', line)
    line = re.sub(r'\\ref[* ]*\{([^}]*)\}', r'ref:\1', line)
    
    # Citations:
    line = re.sub(r'\\cite[pt]*[* ]*\{([^}]*)\}', r'[[cite:&\1]]', line)
    
    # URL:
    line = re.sub(r'\\url[* ]*\{([^}]*)\}', r' \1 ', line)
    line = re.sub(r'\\href[* ]*\{([^}]*)\}\{([^}]*)\}', r' \2 (\1) ', line)
    
    # Bold, italics, etc:
    line = re.sub(r'\\textbf[* ]*\{([^}]*)\}', r'*\1*', line)
    line = re.sub(r'\\textit[* ]*\{([^}]*)\}', r'/\1/', line)
    line = re.sub(r'\\textsc[* ]*\{([^}]*)\}', r'/\1/', line)
    line = re.sub(r'\\emph[* ]*\{([^}]*)\}', r'/\1/', line)
    line = re.sub(r'\\uline[* ]*\{([^}]*)\}', r'_\1_', line)
    
    line = re.sub(r'\{\\bf *([^}]*)\}', r'*\1*', line)
    line = re.sub(r'\{\\it *([^}]*)\}', r'/\1/', line)
    line = re.sub(r'\{\\em *([^}]*)\}', r'/\1/', line)
    line = re.sub(r'\{\\sc *([^}]*)\}', r'/\1/', line)
    
    line = re.sub(r'\\bf\{([^}]*)\}', r'*\1*', line)
    line = re.sub(r'\\it\{([^}]*)\}', r'/\1/', line)
    line = re.sub(r'\\em\{([^}]*)\}', r'/\1/', line)
    line = re.sub(r'\\sc\{([^}]*)\}', r'/\1/', line)
    
    
    # Text:
    line = re.sub(r'\\textrm[* ]*\{([^}]*)\}', r'\1', line)
    
    # Math text:
    line = re.sub(r'\\mathbf[* ]*\{([^}]*)\}', r'*\1*', line)
    line = re.sub(r'\\mathrm[* ]*\{([^}]*)\}', r'\1', line)
    line = re.sub(r' *\\textgreater\{\} *', r' > ', line)
    line = re.sub(r' *\\textless\{\} *', r' < ', line)
    line = re.sub(r'\\textasciicircum\{\}', r'^', line)
    line = re.sub(r'\\textasciicircum', r'^', line)
    
    # Spaces in inline equations:
    line = re.sub(r'^([^\$]*\$) ', r'\1', line)  # Remove space after first $ in line
    line = re.sub(r' (\$[^$]*$)', r'\1', line)   # Remove space before last $ in line
    
    # Inline -> full equations:
    line = re.sub(r'^ *\$([^$]*)\$ *$', r'\[ \1 \]\n', line)  # Replace whole-line $...$ with \[...\]
    line = re.sub(r' +\$ +([^$]+) +\$ +', r'$ \1 $', line)  # Replace leftover " $ text $ " text $"
    
    # Symbols:
    line = re.sub(r' & ', r' | ', line)  # Tabular - CHECK - does this screw up eqnarrays?
    line = re.sub(r'\\\\', r' ', line)   # Tabular or eqnarray
    line = re.sub(r'\\&', r'&', line)
    line = re.sub(r'\\ldots\\*', r'...', line)
    line = re.sub(r'\\LaTeX\\*', r'LaTeX', line)
    line = re.sub(r'\\BibTeX\\*', r'BibTeX', line)
    line = re.sub(r'\.\\ ', r'. ', line)  # Abbreviation
    
    # Fix equations:
    line = re.sub(r'\\int *\\int *\\int', r'\\iiint', line)  # Need amsmath
    line = re.sub(r'\\int *\\int', r'\\iint', line)  # Need amsmath
    line = re.sub(r'\|\|([^|]*)\|\|', r'$\\norm{\1}$', line)  # Absolute value vector ||v|| -> $||v||$
    
    # Footnote: ISSUE: may span multiple lines...
    line = re.sub(r'\\footnote\{([^}]*)\}', r' [fn:1: \1]', line)  # Single-line footnote
    line = re.sub(r'\\footnote\{', r' [fn:1: ', line)  # Left over: multi-line footnote: DiY
    
    # Custom stuff
    # line = re.sub(r'^(.*) *\\tn *$', r'| \1 |', line)  # \tn at end of line for \tabularnewline in cheatography sheets
    line = re.sub(r'^(.*) *\\tn *$', r'\1', line)  # Get rid of the tables
    
    
    # line = re.sub(r'^.*\\.*\n', r'', line)
    # line = re.sub(r'', r'', line)
    
    # line = re.sub(r'[{}]', r'', line)  # Remove leftover braces

    return line


if __name__ == '__main__':
    main()

