#!/bin/bash

##  lessorg:  uses less to display an orgmode file in the terminal with some basic syntax highlighting.
##  2023-01-06, MvdS:  initial version.

# Define colour codes:
# Codes are automatically ended at EoL?  - no '\x1B[0m' needed???
# Note: my default konsole text is already bold?
# https://pueblo.sourceforge.net/doc/manual/ansi_color_codes.html
# https://talyian.github.io/ansicolors/

NULL='\x1B[0m'          # Remove all colours
DEFFG='\x1B[38;5;15m'   # Default foreground colour

BOLD='\x1B[1;38;5;11m'  # Bold: yellow
ITAL='\x1B[3m'          # Italic: italic
ITAL0='\x1B[23m'        # Italic: italics off
ULIN='\x1B[4m'          # Underlined: underlined
ULIN0='\x1B[24m'        # Underlined: underlined off
STRK='\x1B[9m'          # Strikethrough: strikethrough
STRK0='\x1B[29m'          # Strikethrough: strikethrough

H1='\x1B[38;5;87m'   # Light blue
H2='\x1B[38;5;11m'   # Yellow
H3='\x1B[38;5;14m'   # Cyan
H4='\x1B[38;5;208m'  # Orange
H5='\x1B[38;5;10m'   # Light green
H6='\x1B[38;5;48m'   # Light blue-green
H7='\x1B[38;5;254m'  # Light grey
H8='\x1B[38;5;210m'  # Salmon pink.  Then H9=H1, etc.

BLK='\x1B[38;5;208m'  # Block: Orange
CMT='\x1B[38;5;208m'  # Comment: Orange

CODE='\x1B[48;2;60;0;60m'  # CODE: Dark purple BG
MATH='\x1B[48;2;60;0;60m'  # MATH: Dark purple BG

LINK='\x1B[38;5;27m'       # Link text: blue
URL='\x1B[38;5;14m'        # URL: cyan

ENUM='\x1B[48;5;19m'       # Enumerate: blue BG
# TABL='\x1B[38;5;14m'       # Table/hlines: cyan
# TABL='\x1B[48;5;6m'       # Table/hlines: dark cyan BG
TABL='\x1B[48;5;235m\x1B[38;5;14m'  # Table/hlines: cyan FG on dark grey BG


file=`echo "$1.jot" | sed 's|\.jot\.jot|\.jot|g'`  # Add .jot, but remove duplicates


cat $1 \
    | sed \
	  -e "/^\* /s|.*|${H1}&${DEFFG}|" \
	  -e "/^\*\* /s|.*|${H2}&${DEFFG}|" \
	  -e "/^\*\*\* /s|.*|${H3}&${DEFFG}|" \
	  -e "/^\*\*\*\* /s|.*|${H4}&${DEFFG}|" \
	  -e "/^\*\*\*\*\* /s|.*|${H5}&${DEFFG}|" \
	  -e "/^\*\*\*\*\*\* /s|.*|${H6}&${DEFFG}|" \
	  -e "/^\*\*\*\*\*\*\* /s|.*|${H7}&${DEFFG}|" \
	  -e "/^\*\*\*\*\*\*\*\* /s|.*|${H8}&${DEFFG}|" \
	  \
    | sed \
	  -e "s|^ *#+begin_src \(.*\)|${CODE}${BLK}Code block: \u\1${DEFFG}|" \
	  -e "s|^ *#+end_src|${BLK}End code block${NULL}|" \
    | sed \
	  -e "s|\(.* \)\(# .*\)|\1${CMT}\2${DEFFG}|" \
	  -e "s|^ *#|${CMT}&${DEFFG}|" \
	  -e "s|^ *;;|${CMT}&${DEFFG}|" \
    | sed \
	  -e "s:\(^\| \)\*\([^* ][^*]*[^* ]\)\*\( \|$\):\1${BOLD}\2${DEFFG}\3:g" \
	  -e "s:\(^\| \)\*\([^* ]\)\*\( \|$\):\1${BOLD}\2${DEFFG}\3:g" \
	  \
	  -e "s:\(^\| \)/\([^/ ][^/]*[^/ ]\)/\( \|$\):\1${ITAL}\2${ITAL0}\3:g" \
	  -e "s:\(^\| \)/\([^/ ]\)/\( \|$\):\1${ITAL}\2${ITAL0}\3:g" \
	  \
	  -e "s:\(^\| \)_\([^_ ][^_]*[^_ ]\)_\( \|$\):\1${ULIN}\2${ULIN0}\3:g" \
	  -e "s:\(^\| \)_\([^_ ]\)_\( \|$\):\1${ULIN}\2${ULIN0}\3:g" \
	  \
	  -e "s:\(^\| \)+\([^+ ][^+]*[^+ ]\)+\( \|$\):\1${STRK}\2${STRK0}\3:g" \
	  -e "s:\(^\| \)+\([^+ ]\)+\( \|$\):\1${STRK}\2${STRK0}\3:g" \
	  \
	  -e "s:\(^\| \)~\([^~ ][^~]*[^~ ]\)~\( \|$\):\1${CODE}\2${NULL}\3:g" \
	  -e "s:\(^\| \)~\([^~ ]\)~\( \|$\):\1${CODE}\2${NULL}\3:g" \
	  \
	  -e "s:\(^\| \)=\([^= ][^=]*[^= ]\)=\( \|$\):\1${CODE}\2${NULL}\3:g" \
	  -e "s:\(^\| \)=\([^= ]\)=\( \|$\):\1${CODE}\2${NULL}\3:g" \
	  -e "s|^ *: \(.*\)|${CODE}  \1  ${NULL}|g" \
	  \
	  -e "s:\(^\|[ (]\)\$\([^$ ][^$]*[^$ ]\)\$\([ ,.?!:;)]\|$\):\1${MATH}\2${NULL}\3:g" \
	  -e "s:\(^\| \)\$\([^$ ]\)\$\( \|$\):\1${MATH}\2${NULL}\3:g" \
	  -e "/\(^\| \)\\\\\[\( .* \)\\\\\]\( \|$\)/ s:\(^\| \)\\\\\[\( [^]]* \)\\\\\]\( \|$\):\1${MATH} \2 ${NULL}\3:g; \
	     s:~: :g; s: *\\\\\(cos\|sin\|tan\|arccos\|arcsin\|arctan\): \1:g; \
	     s: *\\\\theta *: θ :g; s: *\\\\phi *: φ :g; s: *\\\\pi *: π :g; s: *\\\\rho *: ρ :g; \
	     s: *\\\\frac{\([^}]\)}{\([^}]\)} *: \1/\2 :g; \
	     s: *\\\\frac{\([^}]\)}{\([^}]*\)} *: \1/(\2) :g; \
	     s: *\\\\frac{\([^}]*\)}{\([^}]\)} *: (\1)/\2 :g; \
	     s: *\\\\frac{\([^}]*\)}{\([^}]*\)} *: (\1)/(\2) :g; \
	     s: *\\\\sqrt{\([^}]\)} *: √\1 :g; \
	     s: *\\\\sqrt{\([^}]*\)} *: √(\1) :g;" \
    | sed \
	  -e "s|^ *[+*-] .*|  &|g" \
	  -e "s|^\( *\)\([0-9]*[.)]\)\( .*\)|  \1${ENUM}\2${NULL}\3|g" \
	  -e "s|^\( *[+*-].* ::\)\( .*\)|${BOLD}\1${DEFFG}\2|" \
    | sed \
	  -e "/^ *|---/ s:[|+-]*:${TABL}&${NULL}:g" \
	  -e "/^ *| .* |/ s:|:${TABL}|${NULL}:g" \
	  -e "s:^ *---*\( \|$\):${TABL}----------------------------------------------------------------------------------------------------${NULL}:g" \
	  -e "s: *---*\( \|$\):\n${TABL}----------------------------------------------------------------------------------------------------${NULL}:g" \
    | sed \
	  -e "s|\[\[\(https*://[^] ]*\)\]\[\([^]]*\)\]\]|${LINK}\2: ${URL}\1${DEFFG}|g" \
          -e "s|https*://[^] ]*|${URL}&${DEFFG}|g" \
          -e "s|file:\([^ ][^ ]*\)|file: ${URL}\1${DEFFG}|g" \
	  \
    | less -ir

exit

# MULTILINE bg in code block:
# Need less -r -> unstable (e.g. when scrolling back)
# Need to replace ${NULL} with ${DEFFG} - no major issue
#	  -e "/^ *#+begin_src /s|.*|${CODE}&|" \
#	  -e "/^ *#+end_src/s|.*|&${NULL}|" \
#
# NO multiline bg in code block:
# 	  -e "/^ *#+begin_src /s|.*|${BLK}&|" \
#	  -e "/^ *#+end_src/s|.*|${BLK}&|" \

	  -e "s:\(^\| \)\\\\\[\( [^]]* \)\\\\\]\( \|$\):\1${MATH} \2 ${NULL}\3:g" \

