#!/bin/bash

##  mediawikixml2jotter.sh: convert an xml dump from Mediawiki to jotter
##  2021-11-06, MvdS:  initial version.

# for INFILE in `ls dumpBackup/*.xml`
for INFILE in `ls dumpBackup/LISA_facts_and_data.xml`
do
    OUTFILE=`echo $INFILE | sed -e 's|dumpBackup\/|jotters\/|' -e 's|\.xml|\.jot|' -e 's|_|-|g'`
    echo "$INFILE -> $OUTFILE"
    sed \
	-e '/^  <\/*page>$/d' \
	-e '/^    <ns>0<\/ns>$/d' \
	-e '/^    <id>[0-9]*<\/id>$/d' \
	-e '/^    <\/*revision>$/d' \
	-e '/^      <id>[0-9]*<\/id>$/d' \
	-e '/^      <parentid>[0-9]*<\/parentid>$/d' \
	-e '/^      <\/*contributor>$/d' \
	-e '/^      <model>wikitext<\/model>$/d' \
	-e '/^      <format>text\/x-wiki<\/format>$/d' \
	-e '/^      <comment>.*<\/comment>/d' \
	-e '/^        <ip>[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}<\/ip>/d' \
	-e '/^       <text xml:space="preserve" bytes="[0-9]*">$/d' \
	-e 's|</text>$||' \
	-e '/^      <sha1\/>$/d' \
	-e 's|^    <title>\(.*\)<\/title>$|#+title: \1|' \
	-e 's|^      <timestamp>\(.*\)T\(.*\)Z<\/timestamp>$|#+date: \[\1 \2\] UTC\n|' \
	-e 's|^\*\*\*\*\*\([^\*].*\)$|        - \1|' \
	-e 's|^\*\*\*\*\([^\*].*\)$|      * \1|' \
	-e 's|^\*\*\*\([^\*].*\)$|    - \1|' \
	-e 's|^\*\*\([^\*].*\)$|  - \1|' \
	-e 's|^\*\([^\*].*\)$|+ \1|' \
	-e 's|^=====\([^=].*[^=]\)=====$|***** \1|' \
	-e 's|^====\([^=].*[^=]\)====$|**** \1|' \
	-e 's|^===\([^=].*[^=]\)===$|*** \1|' \
	-e 's|^==\([^=].*[^=]\)==$|** \1|' \
	-e 's|^=\([^=].*[^=]\)=$|* \1|' \
	$INFILE > $OUTFILE
done
